[context.production]
  command = "hugo && node ./themes/engimo/scripts/generate-search-index-algolia.js public/static && ls -ltr search"
  [context.production.environment]
    HUGO_VERSION = "0.53"

[context.deploy-preview]
  command = "hugo --minify --buildDrafts --buildFuture --baseURL /"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.53"

[context.branch-deploy]
  command = "hugo --minify --buildDrafts --buildFuture --baseURL /"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.53"
